[package]
name = "raytracer"
version = "0.5.2"
authors = ["PaperL"]
edition = "2018"

[dependencies]
image = "0.23"
indicatif = "0.16.2"
imageproc = "0.21"
rusttype = "0.9"
rand = "0.8"
console = "0.9.1"
